---
title: "Application workflow and features development"
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
# number-sections: true
# toc: true
# toc-depth: 2
#highlight-style: github
theme: 
  light: flatly
  dark: darkly
format: 
  html: 
    toc-location: left
    embed-resources: true
---

<!-- new section -->

# Step-by-Step app workflow

1.  The app provides a template spreadsheet to download, either directly in the app or in the resources above.

2.  The user fills in the spreadsheet's 4 tabs:

    1.  **User inputs** (user_inputs). Helps offering great flexibility with a minimum number of parameters.

    2.  **Time periods** (time_periods). Describes the times periods covered by the data and how they are combined into reference or reporting.

    3.  **Land use transitions** (AD_lu_transitions). Describes the probability density functions (PDFs) for the land use change areas for each time period

    4.  **Carbon stocks** (c_stocks). Contains the probability density functions for all the carbon elements necessary to associate emission or removal factors to all land use changes and time periods.

3.  The user upload the filled template into the tool.

4.  The app run checks:

    1.  verifies that all connections between time periods, land use changes and carbon elements are correctly entered,

    2.  provides an overview of the data (number of time periods, carbon pools, method for forest degradation, etc.),

    3.  calculates the arithmetic mean of aggregated emission reductions (no simulation yet).

    4.  makes land use change matrices in ha.

5.  If all checks are passed, the app runs the simulations:

    1.  for each PDF, the determined number of simulations is randomly generated, then

    2.  the carbon accounting chain of calculations is created based on the data uploaded,

    3.  the simulations are aggregated to emissions per land use change, emissions and removals per REDD+ activity and time period, emissions reduction and increased removals for each monitoring period in the data.

    4.  The improved estimates and their confidence intervals are reported as the median and quantiles of the simulations at each stage of the aggregation.

6.  A sensitivity analysis is run to provide the respective contributions of REDD+ activities, activity data and emission factors, and time periods to the overall uncertainty.

<!-- new section -->

# Planned features

-   Improve the template guidelines with examples from real cases.

-   Improve the sensitivity analysis.

-   Develop the template tab and calculations for annual processes (removals, soil organic carbon).

-   Develop the template and calculations for bootstrap from raw data.

-   Add truncated PDFs support.

-   Add IPCC tier 1 uncertainties propagation around the arithmetic means.

<!--

Current features:

-   Download a demo template with user inputs, time periods, land use change areas, carbon elements.
-   User filled template submission to the tool,
-   Verification of template integrity,
-   Build calculation chain from input data to greenhouse gas emission reductions (ER)
-   Calculate arithmetic mean ERs from input data
-   Run simulations for all variables and reproduce calculation chain for each simulation
-   Calculate the median of simulated ERs as a better estimate than the arithmetic mean
-   Calculate uncertainty as quantiles of simulations at the chosen level
-   Show medians and confidence intervals at intermediate level (REDD+ activities, activity data and emission factors)
-   Show sansitivity analysis

-->
